### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by LeSoleil-A** [phdymz/ProteinMAE#1]
Hi, thank you for your work! This is an inspiring project and I really wonder when it will be open-sourced. I would really appreciate it if you can also release your code for training downstream tasks. Best wishes!

**Comment by JinyuanSun** [comment]
https://doi.org/10.1093/bioinformatics/btad724 this is the paper.

**Comment by rubenalv** [comment]
@JinyuanSun, @phdymz,  the paper reads that the data and code will be released in this github, when will it be? It looks very exciting!

**Comment by celalp** [comment]
Where is the code?

**Comment by JinyuanSun** [comment]
> @JinyuanSun, @phdymz, the paper reads that the data and code will be released in this github, when will it be? It looks very exciting!

I am not a author of this paper, just found this paper that might provide access to the corresponding authors.

**Comment by rubenalv** [comment]
@JinyuanSun, ah thank you. I contacted the authors re the code release in March via email, but they have not replied.

**Comment by celalp** [comment]
same here

**Comment by JinyuanSun** [comment]
Code just released! Let's use it!
